[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/matugen/generated/spotify-colors.ini'
post_hook = '''
#!/usr/bin/env bash

SOURCE="$HOME/.config/matugen/generated/spotify-colors.ini"
TARGET="$HOME/.config/spicetify/Themes/wal/color.ini"
HASH="$HOME/.cache/spotify-colors.hash"
SPICETIFY="$HOME/.spicetify/spicetify"

mkdir -p "$(dirname "$HASH")"

NEST=$(sha1sum "$SOURCE")

# Skip if unchanged
[[ -f "$HASH" && "$NEST" == "$(<"$HASH")" ]] && exit 0
echo "$NEST" > "$HASH"

(
  mkdir -p "$(dirname "$TARGET")"
  ln -nfs "$SOURCE" "$TARGET"
  "$SPICETIFY" apply -n -q
  hyprctl dispatch sendshortcut "CTRL SHIFT, R, class:^(Spotify)$"
) >/dev/null 2>&1 &
'''
